"""Generated CUAD v1 system prompts by category.

Edit these strings to iterate on prompt variants, then wire the chosen
prompt text back into the evaluator before running a new model_id.
"""

from __future__ import annotations

# Question 1: Document Name
DOCUMENT_NAME_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Document Name" that should be reviewed by a lawyer. Details: The name of the contract\n\nCategory:\nDocument Name\n\nCategory description:\nThe name of the contract\n\nAnswer format:\nContract Name\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 2: Parties
PARTIES_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Parties" that should be reviewed by a lawyer. Details: The two or more parties who signed the contract\n\nCategory:\nParties\n\nCategory description:\nThe two or more parties who signed the contract\n\nAnswer format:\nEntity or individual names\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 3: Agreement Date
AGREEMENT_DATE_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Agreement Date" that should be reviewed by a lawyer. Details: The date of the contract\n\nCategory:\nAgreement Date\n\nCategory description:\nThe date of the contract\n\nAnswer format:\nDate (mm/dd/yyyy)\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 4: Effective Date
EFFECTIVE_DATE_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Effective Date" that should be reviewed by a lawyer. Details: The date when the contract is effective\xa0\n\nCategory:\nEffective Date\n\nCategory description:\nThe date when the contract is effective\n\nAnswer format:\nDate (mm/dd/yyyy)\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 5: Expiration Date
EXPIRATION_DATE_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Expiration Date" that should be reviewed by a lawyer. Details: On what date will the contract\'s initial term expire?\n\nCategory:\nExpiration Date\n\nCategory description:\nOn what date will the contract\'s initial term expire?\n\nAnswer format:\nDate (mm/dd/yyyy) / Perpetual\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 6: Renewal Term
RENEWAL_TERM_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Renewal Term" that should be reviewed by a lawyer. Details: What is the renewal term after the initial term expires? This includes automatic extensions and unilateral extensions with prior notice.\n\nCategory:\nRenewal Term\n\nCategory description:\nWhat is the renewal term after the initial term expires? This includes automatic extensions and unilateral extensions with prior notice.\n\nAnswer format:\n[Successive] number of years/months / Perpetual\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 7: Notice Period to Terminate Renewal
NOTICE_PERIOD_TO_TERMINATE_RENEWAL_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Notice Period To Terminate Renewal" that should be reviewed by a lawyer. Details: What is the notice period required to terminate renewal?\n\nCategory:\nNotice Period to Terminate Renewal\n\nCategory description:\nWhat is the notice period required to terminate renewal?\n\nAnswer format:\nNumber of days/months/year(s)\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 8: Governing Law
GOVERNING_LAW_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Governing Law" that should be reviewed by a lawyer. Details: Which state/country\'s law governs the interpretation of the contract?\n\nCategory:\nGoverning Law\n\nCategory description:\nWhich state/country\'s law governs the interpretation of the contract?\n\nAnswer format:\nName of a US State / non-US Province, Country\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 9: Most Favored Nation
MOST_FAVORED_NATION_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Most Favored Nation" that should be reviewed by a lawyer. Details: Is there a clause that if a third party gets better terms on the licensing or sale of technology/goods/services described in the contract, the buyer of such technology/goods/services under the contract shall be entitled to those better terms?\n\nCategory:\nMost Favored Nation\n\nCategory description:\nIs there a clause that if a third party gets better terms on the licensing or sale of technology/goods/services described in the contract, the buyer of such technology/goods/services under the contract shall be entitled to those better terms?\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 10: Non-Compete
NON_COMPETE_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Non-Compete" that should be reviewed by a lawyer. Details: Is there a restriction on the ability of a party to compete with the counterparty or operate in a certain geography or business or technology sector?\xa0\n\nCategory:\nNon-Compete\n\nCategory description:\nIs there a restriction on the ability of a party to compete with the counterparty or operate in a certain geography or business or technology sector?\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 11: Exclusivity
EXCLUSIVITY_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Exclusivity" that should be reviewed by a lawyer. Details: Is there an exclusive dealing\xa0 commitment with the counterparty? This includes a commitment to procure all “requirements” from one party of certain technology, goods, or services or a prohibition on licensing or selling technology, goods or services to third parties, or a prohibition on\xa0 collaborating or working with other parties), whether during the contract or\xa0 after the contract ends (or both).\n\nCategory:\nExclusivity\n\nCategory description:\nIs there an exclusive dealing\xa0 commitment with the counterparty? This includes a commitment to procure all “requirements” from one party of certain technology, goods, or services or a prohibition on licensing or selling technology, goods or services to third parties, or a prohibition on\xa0 collaborating or working with other parties), whether during the contract or\xa0 after the contract ends (or both).\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 12: No-Solicit of Customers
NO_SOLICIT_OF_CUSTOMERS_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "No-Solicit Of Customers" that should be reviewed by a lawyer. Details: Is a party restricted from contracting or soliciting customers or partners of the counterparty, whether during the contract or after the contract ends (or both)?\n\nCategory:\nNo-Solicit of Customers\n\nCategory description:\nIs a party restricted from contracting or soliciting customers or partners of the counterparty, whether during the contract or after the contract ends (or both)?\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 13: Competitive Restriction Exception
COMPETITIVE_RESTRICTION_EXCEPTION_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Competitive Restriction Exception" that should be reviewed by a lawyer. Details: This category includes the exceptions or carveouts to Non-Compete, Exclusivity and No-Solicit of Customers above.\n\nCategory:\nCompetitive Restriction Exception\n\nCategory description:\nThis category includes the exceptions or carveouts to Non-Compete, Exclusivity and No-Solicit of Customers above.\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 14: No-Solicit of Employees
NO_SOLICIT_OF_EMPLOYEES_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "No-Solicit Of Employees" that should be reviewed by a lawyer. Details: Is there a restriction on a party’s soliciting or hiring employees and/or contractors from the\xa0 counterparty, whether during the contract or after the contract ends (or both)?\n\nCategory:\nNo-Solicit of Employees\n\nCategory description:\nIs there a restriction on a party’s soliciting or hiring employees and/or contractors from the\xa0 counterparty, whether during the contract or after the contract ends (or both)?\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 15: Non-Disparagement
NON_DISPARAGEMENT_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Non-Disparagement" that should be reviewed by a lawyer. Details: Is there a requirement on a party not to disparage the counterparty?\n\nCategory:\nNon-Disparagement\n\nCategory description:\nIs there a requirement on a party not to disparage the counterparty?\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 16: Termination for Convenience
TERMINATION_FOR_CONVENIENCE_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Termination For Convenience" that should be reviewed by a lawyer. Details: Can a party terminate this\xa0 contract without cause (solely by giving a notice and allowing a waiting\xa0 period to expire)?\n\nCategory:\nTermination for Convenience\n\nCategory description:\nCan a party terminate this\xa0 contract without cause (solely by giving a notice and allowing a waiting\xa0 period to expire)?\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 17: Rofr/Rofo/Rofn
ROFR_ROFO_ROFN_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Rofr/Rofo/Rofn" that should be reviewed by a lawyer. Details: Is there a clause granting one party a right of first refusal, right of first offer or right of first negotiation to purchase, license, market, or distribute equity interest, technology, assets, products or services?\n\nCategory:\nRofr/Rofo/Rofn\n\nCategory description:\nIs there a clause granting one party a right of first refusal, right of first offer or right of first negotiation to purchase, license, market, or distribute equity interest, technology, assets, products or services?\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 18: Change of Control
CHANGE_OF_CONTROL_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Change Of Control" that should be reviewed by a lawyer. Details: Does one party have the right to terminate or is consent or notice required of the counterparty if such party undergoes a change of control, such as a merger, stock sale, transfer of all or substantially all of its assets or business, or assignment by operation of law?\n\nCategory:\nChange of Control\n\nCategory description:\nDoes one party have the right to terminate or is consent or notice required of the counterparty if such party undergoes a change of control, such as a merger, stock sale, transfer of all or substantially all of its assets or business, or assignment by operation of law?\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 19: Anti-Assignment
ANTI_ASSIGNMENT_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Anti-Assignment" that should be reviewed by a lawyer. Details: Is consent or notice required of a party if the contract is assigned to a third party?\n\nCategory:\nAnti-Assignment\n\nCategory description:\nIs consent or notice required of a party if the contract is assigned to a third party?\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 20: Revenue/Profit Sharing
REVENUE_PROFIT_SHARING_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Revenue/Profit Sharing" that should be reviewed by a lawyer. Details: Is one party required to share revenue or profit with the counterparty for any technology, goods, or\xa0services?\n\nCategory:\nRevenue/Profit Sharing\n\nCategory description:\nIs one party required to share revenue or profit with the counterparty for any technology, goods, or\xa0services?\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 21: Price Restrictions
PRICE_RESTRICTIONS_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Price Restrictions" that should be reviewed by a lawyer. Details: Is there a restriction on the\xa0 ability of a party to raise or reduce prices of technology, goods, or\xa0 services provided?\n\nCategory:\nPrice Restrictions\n\nCategory description:\nIs there a restriction on the\xa0 ability of a party to raise or reduce prices of technology, goods, or\xa0 services provided?\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 22: Minimum Commitment
MINIMUM_COMMITMENT_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Minimum Commitment" that should be reviewed by a lawyer. Details: Is there a minimum order size or minimum amount or units per-time period that one party must buy from the counterparty under the contract?\n\nCategory:\nMinimum Commitment\n\nCategory description:\nIs there a minimum order size or minimum amount or units per-time period that one party must buy from the counterparty under the contract?\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 23: Volume Restriction
VOLUME_RESTRICTION_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Volume Restriction" that should be reviewed by a lawyer. Details: Is there a fee increase or consent requirement, etc. if one party’s use of the product/services exceeds certain threshold?\n\nCategory:\nVolume Restriction\n\nCategory description:\nIs there a fee increase or consent requirement, etc. if one party’s use of the product/services exceeds certain threshold?\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 24: IP Ownership Assignment
IP_OWNERSHIP_ASSIGNMENT_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Ip Ownership Assignment" that should be reviewed by a lawyer. Details: Does intellectual property created\xa0 by one party become the property of the counterparty, either per the terms of the contract or upon the occurrence of certain events?\n\nCategory:\nIP Ownership Assignment\n\nCategory description:\nDoes intellectual property created\xa0 by one party become the property of the counterparty, either per the terms of the contract or upon the occurrence of certain events?\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 25: Joint IP Ownership
JOINT_IP_OWNERSHIP_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Joint Ip Ownership" that should be reviewed by a lawyer. Details: Is there any clause providing for joint or shared ownership of intellectual property between the parties to the contract?\n\nCategory:\nJoint IP Ownership\n\nCategory description:\nIs there any clause providing for joint or shared ownership of intellectual property between the parties to the contract?\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 26: License Grant
LICENSE_GRANT_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "License Grant" that should be reviewed by a lawyer. Details: Does the contract contain a license granted by one party to its counterparty?\n\nCategory:\nLicense Grant\n\nCategory description:\nDoes the contract contain a license granted by one party to its counterparty?\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 27: Non-Transferable License
NON_TRANSFERABLE_LICENSE_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Non-Transferable License" that should be reviewed by a lawyer. Details: Does the contract limit the ability of a party to transfer the license being granted to a third party?\n\nCategory:\nNon-Transferable License\n\nCategory description:\nDoes the contract limit the ability of a party to transfer the license being granted to a third party?\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 28: Affiliate License-Licensor
AFFILIATE_LICENSE_LICENSOR_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Affiliate License-Licensor" that should be reviewed by a lawyer. Details: Does the contract contain a license grant by affiliates of the licensor or that includes intellectual property of affiliates of the licensor?\xa0\n\nCategory:\nAffiliate License-Licensor\n\nCategory description:\nDoes the contract contain a license grant by affiliates of the licensor or that includes intellectual property of affiliates of the licensor?\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 29: Affiliate License-Licensee
AFFILIATE_LICENSE_LICENSEE_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Affiliate License-Licensee" that should be reviewed by a lawyer. Details: Does the contract contain a license grant to a licensee (incl. sublicensor) and the affiliates of such licensee/sublicensor?\n\nCategory:\nAffiliate License-Licensee\n\nCategory description:\nDoes the contract contain a license grant to a licensee (incl. sublicensor) and the affiliates of such licensee/sublicensor?\n\nAnswer format:\nNo fixed answer format\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 30: Unlimited/All-You-Can-Eat-License
UNLIMITED_ALL_YOU_CAN_EAT_LICENSE_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Unlimited/All-You-Can-Eat-License" that should be reviewed by a lawyer. Details: Is there a clause granting one party an “enterprise,” “all you can eat” or unlimited usage license?\n\nCategory:\nUnlimited/All-You-Can-Eat-License\n\nCategory description:\nIs there a clause granting one party an “enterprise,” “all you can eat” or unlimited usage license?\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 31: Irrevocable or Perpetual License
IRREVOCABLE_OR_PERPETUAL_LICENSE_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Irrevocable Or Perpetual License" that should be reviewed by a lawyer. Details: Does the contract contain a\xa0 license grant that is irrevocable or perpetual?\n\nCategory:\nIrrevocable or Perpetual License\n\nCategory description:\nDoes the contract contain a\xa0 license grant that is irrevocable or perpetual?\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 32: Source Code Escrow
SOURCE_CODE_ESCROW_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Source Code Escrow" that should be reviewed by a lawyer. Details: Is one party required to deposit its source code into escrow with a third party, which can be released to the counterparty upon the occurrence of certain events (bankruptcy,\xa0 insolvency, etc.)?\n\nCategory:\nSource Code Escrow\n\nCategory description:\nIs one party required to deposit its source code into escrow with a third party, which can be released to the counterparty upon the occurrence of certain events (bankruptcy,\xa0 insolvency, etc.)?\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 33: Post-Termination Services
POST_TERMINATION_SERVICES_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Post-Termination Services" that should be reviewed by a lawyer. Details: Is a party subject to obligations after the termination or expiration of a contract, including any post-termination transition, payment, transfer of IP, wind-down, last-buy, or similar commitments?\n\nCategory:\nPost-Termination Services\n\nCategory description:\nIs a party subject to obligations after the termination or expiration of a contract, including any post-termination transition, payment, transfer of IP, wind-down, last-buy, or similar commitments?\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 34: Audit Rights
AUDIT_RIGHTS_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Audit Rights" that should be reviewed by a lawyer. Details: Does a party have the right to\xa0 audit the books, records, or physical locations of the counterparty to ensure compliance with the contract?\n\nCategory:\nAudit Rights\n\nCategory description:\nDoes a party have the right to\xa0 audit the books, records, or physical locations of the counterparty to ensure compliance with the contract?\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 35: Uncapped Liability
UNCAPPED_LIABILITY_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Uncapped Liability" that should be reviewed by a lawyer. Details: Is a party’s liability uncapped upon the breach of its obligation in the contract? This also includes uncap liability for a particular type of breach such as IP infringement or breach of confidentiality obligation.\n\nCategory:\nUncapped Liability\n\nCategory description:\nIs a party’s liability uncapped upon the breach of its obligation in the contract? This also includes uncap liability for a particular type of breach such as IP infringement or breach of confidentiality obligation.\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 36: Cap on Liability
CAP_ON_LIABILITY_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Cap On Liability" that should be reviewed by a lawyer. Details: Does the contract include a cap on liability upon the breach of a party’s obligation? This includes time limitation for the counterparty to bring claims or maximum amount for recovery.\n\nCategory:\nCap on Liability\n\nCategory description:\nDoes the contract include a cap on liability upon the breach of a party’s obligation? This includes time limitation for the counterparty to bring claims or maximum amount for recovery.\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 37: Liquidated Damages
LIQUIDATED_DAMAGES_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Liquidated Damages" that should be reviewed by a lawyer. Details: Does the contract contain a clause that would award either party liquidated damages for breach or a fee upon the termination of a contract (termination fee)?\n\nCategory:\nLiquidated Damages\n\nCategory description:\nDoes the contract contain a clause that would award either party liquidated damages for breach or a fee upon the termination of a contract (termination fee)?\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 38: Warranty Duration
WARRANTY_DURATION_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Warranty Duration" that should be reviewed by a lawyer. Details: What is the duration of any\xa0 warranty against defects or errors in technology, products, or services\xa0 provided under the contract?\n\nCategory:\nWarranty Duration\n\nCategory description:\nWhat is the duration of any\xa0 warranty against defects or errors in technology, products, or services\xa0 provided under the contract?\n\nAnswer format:\nNumber of months or years\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 39: Insurance
INSURANCE_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Insurance" that should be reviewed by a lawyer. Details: Is there a requirement for insurance that must be maintained by one party for the benefit of the counterparty?\n\nCategory:\nInsurance\n\nCategory description:\nIs there a requirement for insurance that must be maintained by one party for the benefit of the counterparty?\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 40: Covenant Not to Sue
COVENANT_NOT_TO_SUE_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Covenant Not To Sue" that should be reviewed by a lawyer. Details: Is a party restricted from contesting the validity of the counterparty’s ownership of intellectual property or otherwise bringing a claim against the counterparty for matters unrelated to the contract?\n\nCategory:\nCovenant Not to Sue\n\nCategory description:\nIs a party restricted from contesting the validity of the counterparty’s ownership of intellectual property or otherwise bringing a claim against the counterparty for matters unrelated to the contract?\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

# Question 41: Third Party Beneficiary
THIRD_PARTY_BENEFICIARY_SYSTEM_PROMPT = 'You are a legal contract review assistant evaluating CUAD clauses.\n\nTask:\nHighlight the parts (if any) of this contract related to "Third Party Beneficiary" that should be reviewed by a lawyer. Details: Is there a non-contracting party who is a beneficiary to some or all of the clauses in the contract and therefore can enforce its rights against a contracting party?\n\nCategory:\nThird Party Beneficiary\n\nCategory description:\nIs there a non-contracting party who is a beneficiary to some or all of the clauses in the contract and therefore can enforce its rights against a contracting party?\n\nAnswer format:\nYes/No\n\nInstructions:\n- Read the provided contract title and contract text.\n- Return exact answer text span(s) from the contract when present.\n- Separate multiple answer spans with newlines.\n- Return NO_ANSWER when the contract does not contain an answer.\n- Set marked_impossible to true only when no answer is present.'

CATEGORY_SYSTEM_PROMPTS = {
    'Document Name': DOCUMENT_NAME_SYSTEM_PROMPT,
    'Parties': PARTIES_SYSTEM_PROMPT,
    'Agreement Date': AGREEMENT_DATE_SYSTEM_PROMPT,
    'Effective Date': EFFECTIVE_DATE_SYSTEM_PROMPT,
    'Expiration Date': EXPIRATION_DATE_SYSTEM_PROMPT,
    'Renewal Term': RENEWAL_TERM_SYSTEM_PROMPT,
    'Notice Period to Terminate Renewal': NOTICE_PERIOD_TO_TERMINATE_RENEWAL_SYSTEM_PROMPT,
    'Governing Law': GOVERNING_LAW_SYSTEM_PROMPT,
    'Most Favored Nation': MOST_FAVORED_NATION_SYSTEM_PROMPT,
    'Non-Compete': NON_COMPETE_SYSTEM_PROMPT,
    'Exclusivity': EXCLUSIVITY_SYSTEM_PROMPT,
    'No-Solicit of Customers': NO_SOLICIT_OF_CUSTOMERS_SYSTEM_PROMPT,
    'Competitive Restriction Exception': COMPETITIVE_RESTRICTION_EXCEPTION_SYSTEM_PROMPT,
    'No-Solicit of Employees': NO_SOLICIT_OF_EMPLOYEES_SYSTEM_PROMPT,
    'Non-Disparagement': NON_DISPARAGEMENT_SYSTEM_PROMPT,
    'Termination for Convenience': TERMINATION_FOR_CONVENIENCE_SYSTEM_PROMPT,
    'Rofr/Rofo/Rofn': ROFR_ROFO_ROFN_SYSTEM_PROMPT,
    'Change of Control': CHANGE_OF_CONTROL_SYSTEM_PROMPT,
    'Anti-Assignment': ANTI_ASSIGNMENT_SYSTEM_PROMPT,
    'Revenue/Profit Sharing': REVENUE_PROFIT_SHARING_SYSTEM_PROMPT,
    'Price Restrictions': PRICE_RESTRICTIONS_SYSTEM_PROMPT,
    'Minimum Commitment': MINIMUM_COMMITMENT_SYSTEM_PROMPT,
    'Volume Restriction': VOLUME_RESTRICTION_SYSTEM_PROMPT,
    'IP Ownership Assignment': IP_OWNERSHIP_ASSIGNMENT_SYSTEM_PROMPT,
    'Joint IP Ownership': JOINT_IP_OWNERSHIP_SYSTEM_PROMPT,
    'License Grant': LICENSE_GRANT_SYSTEM_PROMPT,
    'Non-Transferable License': NON_TRANSFERABLE_LICENSE_SYSTEM_PROMPT,
    'Affiliate License-Licensor': AFFILIATE_LICENSE_LICENSOR_SYSTEM_PROMPT,
    'Affiliate License-Licensee': AFFILIATE_LICENSE_LICENSEE_SYSTEM_PROMPT,
    'Unlimited/All-You-Can-Eat-License': UNLIMITED_ALL_YOU_CAN_EAT_LICENSE_SYSTEM_PROMPT,
    'Irrevocable or Perpetual License': IRREVOCABLE_OR_PERPETUAL_LICENSE_SYSTEM_PROMPT,
    'Source Code Escrow': SOURCE_CODE_ESCROW_SYSTEM_PROMPT,
    'Post-Termination Services': POST_TERMINATION_SERVICES_SYSTEM_PROMPT,
    'Audit Rights': AUDIT_RIGHTS_SYSTEM_PROMPT,
    'Uncapped Liability': UNCAPPED_LIABILITY_SYSTEM_PROMPT,
    'Cap on Liability': CAP_ON_LIABILITY_SYSTEM_PROMPT,
    'Liquidated Damages': LIQUIDATED_DAMAGES_SYSTEM_PROMPT,
    'Warranty Duration': WARRANTY_DURATION_SYSTEM_PROMPT,
    'Insurance': INSURANCE_SYSTEM_PROMPT,
    'Covenant Not to Sue': COVENANT_NOT_TO_SUE_SYSTEM_PROMPT,
    'Third Party Beneficiary': THIRD_PARTY_BENEFICIARY_SYSTEM_PROMPT,
}
